init:
  appId: "516d68fc28e06bb7b8000040"
  orgUrl: "https://hull-demos.hullapp.io"
  debug: false
  sources:
    default: '.'
components:
  form:
    id: "entity:formidable"
  builder:
    id: "entity:formidable"
